name: Hello World Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/chechkout@v2
      - name: Hello World
        run: echo "Hello World"
        shell: bash
  
  goodbye: 
    runs_on: ubuntu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash
